---
id: 20220217_promise
title: Promise 101
subtitle: 什么是 callback 陷阱，为什么会提出 Promise，Promise 和 then/catch 链式调用 还有 async/await 语法糖有什么关系
subject: Promise
category: 概念理解
tags: promise
keywords: javascript;es;promise;then catch;async await
level: 100
cover: https://media.inkscape.org/media/resources/file/Koi_carp_2.svg
videos: https://qiniuargus.weready.online/blog/sharing/video/2022-03-11-promise-101.mp4
authors: Chris Wei
created_when: 2022-02-17
updated_when: 2022-03-11
---

# Promise 101

## 最早的纯 `js` 非阻塞编程带来的 `callback` 陷阱（地狱）

- 带有 `callback` 入参的函数模拟

> 这里创建一个函数 `fnDemoCallback`，用于模拟第三方提供的以异步方式执行的函数。函数内部使用 `setTimeout`，模拟一个耗时的操作。调用函数需要提供 `callback` 回调函数的方式获取函数执行结果。

```
const fnDemoCallback = (param, fnCallback) => {
  setTimeout(() => {
    if (
      (typeof param !== 'number') ||
      (param < 60)
    ) {
      fnCallback(new Error(`Paramter error! [${param}]`))
    } 
    else {
      fnCallback(`You input is ${param}`)
    }
  }, 300);
}
```

- 函数的使用

> 这里我们只用最最原始的 `js` `callback` 回调语法

```
function demoCallback() {
  fnDemoCallback(80, (result80) => {
    if (result80 instanceof Error) {
      console.error(result80)
      return
    }

    console.log(result80)
    fnDemoCallback(70, (result70) => {
      if (result70 instanceof Error) {
        console.error(result70)
        return
      }

      console.log(result70)
      fnDemoCallback(60, (result60) => {
        if (result60 instanceof Error) {
          console.error(result60)
          return
        }

        console.log(result60)
        fnDemoCallback(50, (result50) => {
          if (result50 instanceof Error) {
            console.error(result50)
            return
          }

          console.log(result60)
        })
      })
    })
  })
}
```

- 上面的函数如果执行，相应的结果

```
demoCallback()

/**
You input is 80
You input is 70
You input is 60
Error: Paramter error! [50]
 */
```

## 同样的情况，如果引入 `Promise`，则可以回避 `callback` 陷阱（地狱）

- 函数

```
const fnDemoPromise = (param) => new Promise((resolve, reject) => {
  setTimeout(() => {
    if (
      (typeof param !== 'number') ||
      (param < 60)
    ) {
      reject(new Error(`Paramter error! ${param}`))
    } 
    else {
      resolve(`You input is ${param}`)
    }
  }, 300);
})
```

- 函数的使用

> 这里我们使用 `ES` 的 `then/catch` 链式调用，代码整洁了很多

```
function demoPromiseThen() {
  fnDemoPromise(80)
  .then((result) => {
    console.log(result)
    return fnDemoPromise(70)
  })
  .then((result) => {
    console.log(result)
    return fnDemoPromise(60)
  })
  .then((result) => {
    console.log(result)
    return fnDemoPromise(50)
  })
  .then((result) => {
    console.log(result)
  })
  .catch((err) => {
    console.error(err)
  })
}
```

- 上面的函数如果执行，相应的结果

```
demoPromiseThen()

/**
You input is 80
You input is 70
You input is 60
Error: Paramter error! [50]
 */
```

## 针对同样的 `fnDemoPromise` 函数，如果使用 `async/await` 语法糖

- 函数的使用，可以这样

```
async function demoPromiseAwait8765() {
  try {
    console.log(await fnDemoPromise(80))
    console.log(await fnDemoPromise(70))
    console.log(await fnDemoPromise(60))
    console.log(await fnDemoPromise(50))
  }
  catch(err) {
    console.error(err)
  }
}
```

- 也可以这样

```
async function demoPromiseAwaitLoop() {
  try {
    for (let p = 80; p > 0; p-=10) {
      let result = await fnDemoPromise(p)
      console.log(result)
    }
  }
  catch(err) {
    console.error(err)
  }
}
```

- 上面的函数如果执行，无论是 `demoPromiseAwait8765`，还是 `demoPromiseAwaitLoop` 相应的结果一样

```
/**
You input is 80
You input is 70
You input is 60
Error: Paramter error! [50]
 */
```

## 视频概要

- 常规函数，通过 `return` 返回结果
- 通过回调函数返回结果
- 依赖 `CPU` 执行的常规计算任务 vs. 依赖外部设备执行的 `IO` 任务
- 同步阻塞式 vs. 异步非阻塞
- 异常处理
- 回调地狱
- 通过 `Promise` 改造通过 回调函数 返回结果的异步非阻塞函数
- `then/catch` 链条获取 `Promise` 的 `resolve` 或 `reject` 结果
- `await/async` 把 异步非阻塞 在代码写法上改造为 同步阻塞
- `await/async` 在实际执行上，仍然具有 异步非阻塞 的效率
- `await/async` 实现循环式调用
- 通过 `Promise.all` 实现多个异步函数并发抢占式运行
